# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0002_auto_20190417_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_content_wrap',
            name='entry_header_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero_content_wrap',
            name='entry_image',
            field=models.FileField(upload_to=b'hero_content_wrap'),
        ),
    ]
