# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0003_auto_20190418_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_icon_boxes',
            name='entry_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero_icon_boxes',
            name='image_name_grey',
            field=models.FileField(upload_to=b'hero_icon_boxes'),
        ),
        migrations.AlterField(
            model_name='hero_icon_boxes',
            name='image_name_white',
            field=models.FileField(upload_to=b'hero_icon_boxes'),
        ),
        migrations.AlterField(
            model_name='home_page_welcome',
            name='entry_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home_page_welcome',
            name='image_welcome',
            field=models.FileField(upload_to=b'home_page_welcome'),
        ),
    ]
