# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-19 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0004_auto_20190418_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_breaking_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_content', models.TextField()),
                ('news_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='consult_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 19, 15, 8, 35, 960842, tzinfo=utc), upload_to=b'base_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='logo_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 19, 15, 8, 57, 820945, tzinfo=utc), upload_to=b'base_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='scan_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 19, 15, 9, 6, 245936, tzinfo=utc), upload_to=b'base_info'),
            preserve_default=False,
        ),
    ]
