# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0005_auto_20190419_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_content', models.TextField()),
                ('news_time', models.DateTimeField()),
                ('news_image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
