# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0006_all_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', models.TextField()),
                ('about_image', models.FileField(upload_to=b'')),
                ('content_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('words', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
