# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0007_aboutus_leaderwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_image',
            field=models.FileField(upload_to=b'about_us'),
        ),
        migrations.AlterField(
            model_name='all_news',
            name='news_image',
            field=models.FileField(upload_to=b'all_news'),
        ),
    ]
