# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0009_auto_20190421_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderwords',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leaderwords',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
