# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 02:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0010_auto_20190421_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderwords',
            old_name='name',
            new_name='leader_name',
        ),
        migrations.RenameField(
            model_name='leaderwords',
            old_name='type',
            new_name='leader_type',
        ),
        migrations.RenameField(
            model_name='leaderwords',
            old_name='words',
            new_name='leader_words',
        ),
        migrations.AddField(
            model_name='leaderwords',
            name='leader_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 21, 2, 2, 17, 704147, tzinfo=utc), upload_to=b'leader_words'),
            preserve_default=False,
        ),
    ]
