# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0012_auto_20190421_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='company_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 21, 2, 53, 2, 216433, tzinfo=utc), upload_to=b'base_info'),
            preserve_default=False,
        ),
    ]
