# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0013_baseinfo_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingParter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('current_image', models.FileField(upload_to=b'')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='winwin_description',
            field=models.TextField(default=datetime.datetime(2019, 4, 21, 3, 13, 46, 224784, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='winwin_image',
            field=models.FileField(default=datetime.datetime(2019, 4, 21, 3, 13, 52, 869486, tzinfo=utc), upload_to=b'base_info'),
            preserve_default=False,
        ),
    ]
