# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0015_applicationform_targetandrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
