# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xinjingshifangzhou', '0017_leavenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='email',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='applicationform',
            old_name='school',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='height',
        ),
    ]
